# .github/workflows/sagemaker-deploy.yml
name: SageMaker Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: my-mlops-project-aq
      ENDPOINT_NAME: iris-endpoint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Train model
        working-directory: ./model
        run: |
          python train.py
          tar -czvf model.tar.gz model.pkl

      - name: Upload model to S3
        run: |
          aws s3 cp ./model/model.tar.gz s3://${{ env.S3_BUCKET }}/model/model.tar.gz

      - name: Delete existing SageMaker endpoint if exists
        run: |
          # Delete endpoint if it exists
          if aws sagemaker describe-endpoint --endpoint-name $ENDPOINT_NAME > /dev/null 2>&1; then
              echo "Endpoint exists. Deleting endpoint..."
              aws sagemaker delete-endpoint --endpoint-name $ENDPOINT_NAME
              
              # Wait until endpoint deletion completes
              aws sagemaker wait endpoint-deleted --endpoint-name $ENDPOINT_NAME
              
              # Delete endpoint config
              config_name=$(aws sagemaker describe-endpoint --endpoint-name $ENDPOINT_NAME --query "EndpointConfigName" --output text)
              if [ "$config_name" != "None" ]; then
                  echo "Deleting endpoint config $config_name"
                  aws sagemaker delete-endpoint-config --endpoint-config-name $config_name
              fi
          else
              echo "Endpoint does not exist. Proceeding..."
          fi

      - name: Deploy model to SageMaker
        run: python deploy.py
